# These are supported funding model platforms

github: [opprDev]
patreon: oppr
open_collective: oppr
ko_fi: opprGroup
tidelift: npm/cornerstone-core
community_bridge: 67d0a58f-cfd0-40b8-bd08-e13d96304c13
liberapay: oppr
issuehunt: mimbcdui
otechie: oppr
custom: ['https://paypal.me/oppr']
